### ISSUE TITLE
this.options.authnContext.forEach is not a function

### ISSUE THREAD

**Issue by eladeyal-intel** [sqlpad/sqlpad#1068]
My setup works with v5.1.0 but fails with v6.8.1 (and `latest`)

I use SAML and after clicking "login with SAML", I'm navigated to `/auth/saml` and get this.

It's possible that I needed to do some env var reconfiguration, but I would expect an explicit error message if so.

```
TypeError: this.options.authnContext.forEach is not a function                                                                               
    at SAML.generateAuthorizeRequestAsync (/usr/app/node_modules/passport-saml/lib/node-saml/saml.js:216:39)                                 
    at SAML.getAuthorizeUrlAsync (/usr/app/node_modules/passport-saml/lib/node-saml/saml.js:407:36)                                          
    at login-request (/usr/app/node_modules/passport-saml/lib/passport-saml/strategy.js:106:60)                                              
    at Strategy.authenticate (/usr/app/node_modules/passport-saml/lib/passport-saml/strategy.js:129:13)                                      
    at attempt (/usr/app/node_modules/passport/lib/middleware/authenticate.js:366:16)                                                        
    at authenticate (/usr/app/node_modules/passport/lib/middleware/authenticate.js:367:7)                                                    
    at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)                                             
    at next (/usr/app/node_modules/express/lib/router/route.js:137:13)                                                                       
    at Route.dispatch (/usr/app/node_modules/express/lib/router/route.js:112:3)                                                              
    at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)                                             
    at /usr/app/node_modules/express/lib/router/index.js:281:22                                                                              
    at Function.process_params (/usr/app/node_modules/express/lib/router/index.js:335:12)                                                    
    at next (/usr/app/node_modules/express/lib/router/index.js:275:10)                                                                       
    at Function.handle (/usr/app/node_modules/express/lib/router/index.js:174:3)                                                             
    at router (/usr/app/node_modules/express/lib/router/index.js:47:12)                                                                      
    at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)                                             
```

I do have value for `SQLPAD_SAML_AUTH_CONTEXT`

I also see this, but I imagnie it's just feedback from above
```
Error: failed with status code 500
at ServerResponse.onResFinished (/usr/app/node_modules/pino-http/logger.js:73:38)
at ServerResponse.emit (events.js:412:35)
at ServerResponse.emit (domain.js:470:12)
at onFinish (_http_outgoing.js:792:10)
at callback (internal/streams/writable.js:513:21)
at afterWrite (internal/streams/writable.js:466:5)
at afterWriteTick (internal/streams/writable.js:453:10)
at processTicksAndRejections (internal/process/task_queues.js:81:21)"},"responseTime":2,"msg":"request errored"}         
```

**Comment by eladeyal-intel** [comment]
any help will be appreciated @rickbergfalk

**Comment by eladeyal-intel** [comment]
I did go over the documentation changes between abovementioned versions and I think I'm OK,

**Comment by rickbergfalk** [comment]
Sorry about that @eladeyal-intel. There was a major version bump for the passport-saml between the 2 versions, and I'm wondering if there are some additional configs that need to be set. 

The 500 status code is definitely from the TypeError thrown from the initial error.

**Comment by rickbergfalk** [comment]
#1067 might have this fixed!

**Comment by eladeyal-intel** [comment]
@rickbergfalk is it not time for 6.8.2 ? thanks

**Comment by rickbergfalk** [comment]
@eladeyal-intel yeah sorry about that - should have tagged a new version a lot sooner. tagged 6.9.0 since there have been some additions
